#!/bin/bash

##########
# This file is intended for custom scripts to run on each terminal session load.
##########

# Import user scripts.
USER_SCRIPTS="$HOME/.bashscripts"
if [[ -e $USER_SCRIPTS ]] && [[ -d $USER_SCRIPTS ]]
then
  for f in $USER_SCRIPTS
  do
    source $f
  done
fi

# Set Lynx homepage to DuckDuckGo Lite.
export WWW_HOME="https://ddg.gg/lite"

# Fork a specified process and suppress stderr.
function fork {
  $* 2> /dev/null &
}

# Fork a process and ignore SIGHUP.
function nhfork {
  nohup $* > /dev/null 2>&1 &
}

# CLI mode (e.g. Raspberry Pi minimal): check battery
function battery {
  upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -B1 percentage
}

##########
# Crosh scripts for launching Crouton.
##########

#DISTRO="stretch"
#DESKENV="startxfce4"

# Boot Crouton distro in terminal/CLI mode.
#function gnu {
#  sudo enter-chroot -n $DISTRO
#}

# Boot Crouton distro in full GUI mode.
#function gnux {
#  sudo $DESKENV -X xorg
#}

# Boot Crouton distro in XIWI tab.
#function gnuw {
#  sudo $DESKENV -X xiwi
#}

# Inside chroot: create new ChromeOS tab with app.
#function cr-gui {
#  xiwi $* &> /dev/null &
#}
