#!/usr/bin/env bash

##########
# This file is intended for custom scripts to run on each terminal session load.
##########

# Import user scripts.
USER_SCRIPTS="$HOME/.bashscripts"
if [[ -e $USER_SCRIPTS ]] && [[ -d $USER_SCRIPTS ]]
then
  pushd $USER_SCRIPTS > /dev/null
  for f in $(/usr/bin/env ls -A1)
  do
    source $USER_SCRIPTS/$f
  done
  popd > /dev/null
fi

# Fork a specified process and suppress stderr.
function fork {
  $* 2> /dev/null &
}

# Fork a process and ignore SIGHUP.
function nhfork {
  nohup $* > /dev/null 2>&1 &
}

