#!/usr/bin/env bash

##########
# This file is intended for custom scripts to run on each terminal session load.
##########

# Import user scripts.
USER_SCRIPTS="$HOME/.bashscripts"
if [[ -e $USER_SCRIPTS ]] && [[ -d $USER_SCRIPTS ]]
then
  for f in $(ls -A1 $USER_SCRIPTS)
  do
    source $USER_SCRIPTS/$f
  done
fi

# Set Lynx homepage to DuckDuckGo Lite.
export WWW_HOME="https://ddg.gg/lite"

# Fork a specified process and suppress stderr.
function fork {
  $* 2> /dev/null &
}

# Fork a process and ignore SIGHUP.
function nhfork {
  nohup $* > /dev/null 2>&1 &
}

# CLI mode (e.g. Raspberry Pi minimal): check battery
case $(uname -s) in
  *Linux*)
    function battery {
      upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -B1 percentage
    }
  ;;
esac

