#!/bin/bash

##########
# This file is intended for BSD and variants, including macOS.
# This will set the colors of files, folders, &c when calling `ls`.
# The full list of currently set LSCOLORS can be found by running:
#
# echo $LSCOLORS
##########

##########
# BSD AND MACOS LSCOLOR COLDES
##########

BSD_K="a"
BSD_R="b"
BSD_G="c"
BSD_Y="d"
BSD_B="e"
BSD_M="f"
BSD_C="g"
BSD_W="h"
BSD_BK="A"
BSD_BR="B"
BSD_BG="C"
BSD_BY="D"
BSD_BB="E"
BSD_BM="F"
BSD_BC="G"
BSD_BW="H"
BSD_D="x"
