#!/usr/bin/env bash

#####
# APT packages
#####
# xfonts-terminus
# git
# xscreensaver xscreensaver-data-extra (xscreensaver-data)
# default-jdk
# dnsutils
# vim
# gcc, g++
# faenza-icon-theme
# freeglut3-dev
# gdb
# htop
# python3
# idle3 python3-pip
# manpages manpages-dev
# lshw lshw-gtk
# arc-theme
# fonts-ubuntu fonts-ubuntu-console
# tree
# xfce4-goodies
# xinput xcalib
# ant
# curl
# gvfs-fuse gvfs-backends
# xsltproc
# xmllint
# openssh-server
# yelp
# geany
# nodejs npm
# php7.2-fpm php7.2
# heroku
# xfwm4-themes (?)
# plank
# gdebi

#####
# Other APT packages
#####
# vokoscreen
# onboard
# gparted
# musescore
# milkytracker
# gimp
# mtpaint
# timidity timidity-interfaces-extra 
# gpick
# arduino
# qpdf

#####
# Other packages
#####
# android studio
# cling
# cm-uncode

#####
# Crouton: Fix ~/Downloads write issue
#####
# Comment out "session optional pam_keyinit.so force revoke"
sudo vim /etc/pam.d/runuser-l
sudo vim /etc/pam.d/su-l

#####
# Terminal
#####
xterm -title "XTerm" -fa "Terminus" -fs 12 -bg "black" -fg "white" -bc +bdc -cr "green" -ms "red" -e "/bin/bash" -l

#####
# SSH
#####
ssh-keygen
ssh-copy-id -i -p<port> <username>@<ipaddress>

#####
# Configuration
#####
git clone https://github.com/ascenderx/termconfig.git .termconfig
~/.termconfig/genlinks.sh

